config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "users#index"
  
  devise_scope :user do 
    authenticated :user do 
      root 'users#index', as: :authenticated_root 
    end
    unauthenticated do 
      root 'devise/sessions#new', as: :unauthenticated_root 
    end 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post '/users/:user_id/add_like/:id' =>  'posts#index', as: :like

  resources :users, only: %i[index show] do 
    resources :posts, only: %i[index new create show]
  end

  resources :posts do
    resources :comments, only: %i[create]
    resources :likes, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.size)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes

  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_post_counter

  def update_post_counter
    user.update(posts_counter: user.posts.size)
  end

  def recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts
  has_many :comments
  has_many :likes

  def recent_posts
    posts.last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(text: params[:comment][:text], user_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to user_post_path(@post.user.id, @post.id), notice: 'Comment created successfully'
        else
          redirect_to user_post_path(@post.user.id, @post.id), alert: 'An error occured, please try again!'
        end
      end
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(user_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_path(@post.user.id, @post.id), notice: 'Liked 👍'
        else
          redirect_to user_post_path(@post.user.id, @post.id), alert: 'An error occured, please try again!'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    user_id = params[:user_id] || 1
    @user = User.includes(:posts).find(user_id) || {}
  end

  def show
    user_id = params[:user_id]
    post_id = params[:id]
    @user = User.find(user_id)
    @post = @user.posts.includes(:comments, :likes).where(id: post_id).first
  end

  def new
    @current = current_user
  end

  def create
    new_post = current_user.posts.build(post_params)

    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to user_posts_path(new_post.user_id), notice: 'Post created successfully'
        else
          render :new, alert: 'An error occured. Please try again!'
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_img(user)
    dummy_avatars = []
    dummy_avatars << '/assets/dummy_avatar_1.png'
    dummy_avatars << '/assets/dummy_avatar_2.png'
    dummy_avatars << '/assets/dummy_avatar_3.png'
    dummy_avatars << '/assets/dummy_avatar_4.png'
    dummy_avatars << '/assets/dummy_avatar_5.png'
    dummy_avatars << '/assets/dummy_avatar_6.png'
    dummy_avatars << '/assets/dummy_avatar_7.png'
    dummy_avatars << '/assets/dummy_avatar_8.png'
    dummy_avatars << '/assets/dummy_avatar_9.png'
    dummy_avatars << '/assets/dummy_avatar_10.png'
    user.photo.present? ? user.photo : dummy_avatars.sample
  end
end

app/views/comments/_create.html.erb
<section class="container mt-5 p-2 bio">
  <%= form_with model:[@post, @post.comments.build], method: :post, local: true, id: 'new-comment-form' do |f| %>
    <%= f.label :text, "comment", class: "form-label fs-6" %><br>
    <%= f.text_area :text, size:"50x5", class: "form-control", placeholder: "Write your comment here...", required: true %>
    <br>
    <%= f.submit "Add comment", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    
    <%= stylesheet_link_tag "application", "data-turbo-track": "none" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body-blog" id="body-blog">
  
    <% if notice %>
      <p class="alert alert-success text-center msg"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js" integrity="sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.3/dist/js/bootstrap.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</html>

app/views/likes/_create.html.erb
<section>
  <%= form_tag like_path(@post.user.id, @post.id) do%>
      <%= submit_tag  "Like post" , data: {disable_with: "👍"}, class: "btn btn-success mb-3"%>
  <%end%>
</section>

app/views/posts/index.html.erb
<div>
 <nav class="fs-6 p-3 container mt-2 p-2 bio">
    <%= link_to "Add a post", new_user_post_path(@user.id) %> | 
    <%= link_to "Home", root_path %> | 
    <%= link_to "Back", :back %>
  </nav>
  <%= render partial: "users/user_profile", locals: { user: @user } %>
    <ul>
      <% @user.posts.each do |p| %>
        <li>
          <div class="border border-3 border-dark container mt-5 p-2 bio">
            <%= link_to user_post_path(@user.id, p.id), id: "user_post#{p.id}" do %>
            <h4><%= p.title%></h4>
            <% end %>
            <p><%= h(p.text) %></p>
            <div>
              <span>Comments: <%= p.comments.size %></span>
              <span>Likes: <%= p.comments.size %></span>
            </div>
          </div>
          <div>
            <ul class="border border-1 border-dark container p-2 mt-1 bio">
              <% p.recent_comments.each do |c| %>
              <li><%= c.user.name %>: <%= h(c.text) if c.text %></li>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    </ul>
  <button class="btn btn-primary d-flex justify-content-center align-self-center my-5 button display">Pagination</button>
</div>

app/views/posts/new.html.erb
<nav class="fs-6 p-3 container mt-2 p-2 bio"><%= link_to "Back", :back %></nav>
<h3 class="fs-2 p-3 container mt-2 p-2 bio"> Create Your Post</h3>
<section class="fs-4 p-3 border border-1 container mt-5 p-2 bio">
  <%= form_with model:[@current, @current.posts.build], method: :post, local: true, id: 'new-post-form' do |f| %>
    <%= f.label :title, "Title", class: "form-label fs-6" %>
    <%= f.text_field :title, :placeholder => "Title goe here...", required: true, class: "form-control mb-4" %>
    <%= f.label :text, "Write a new post", class: "form-label fs-6" %>
    <%= f.text_area :text, size: "80x15", :placeholder => "Add your post here...", required: true, class: "form-control" %>
    <%= f.submit "Add Post", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<nav class="fs-6 p-3 container mt-2 p-2 bio">
  <%= link_to "Home", root_path %>
</nav>

<div>
  <div>
    <div class="border border-3 border-dark container p-2 my-5 bio">
      <div class="d-flex justify-content-between my-3">
        <h4><%= @post.title %> by <%= link_to user_path(@post.user.id) do %> <%= @post.user.name %> <% end %></h4>
        <p>Comments : <%= @post.comments.size%>  Likes : <%= @post.likes.size %> </p>
      </div>
        <p><%= h(@post.text) %> </p>
    </div>

    <ul class="border border-2 border-dark container p-2 my-5 bio">
      <% @post.comments.each do |c| 
        next if c.text.nil?
        %>
        <li><%= c.user.name %>: <%= h(c.text) %></li>
      <% end %>
    </ul>

    <%= render partial: "likes/create" %>
    <%= render partial: "comments/create" %>

    
    
</div>

app/views/users/_user_profile.html.erb
<section>
  <div class="display mt-5">
    <%# <%= image_tag user_img(''), :class => "avatar border border-2 border-dark" %>
    <div class="user_list border border-1 border-dark d-flex justify-content-between py-5">
      <h2 class="user_name"><%= user.name %></h2>
      <p class="num_post flex-row-reverse fs-6 mt-4">Number of posts: <%= user.posts.size %></p>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div>
 <ul class="nav justify-content-center bg-light text-white">
  <li class="nav-item">
    <%= link_to(destroy_user_session_path, {:class => "nav-link", :method => :delete}) do  %>
      <span class="sidebar-normal"> Logout </span>
    <% end %> 
  </li>
  <li class="nav-item">
   <%= link_to "Settings", edit_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
   <%= link_to "Profile", current_user, class: 'nav-link' %>
  </li>
  </ul>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <%= render partial: "user_profile", locals: {user: user} %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <nav class="fs-6 p-3 container mt-2 p-2 bio">
  <%= link_to "Home", root_path %>
  </nav>
  <%= render partial: "user_profile", locals: {user: @user} %>
  <div class="border border-1 border-dark container p-2 my-5 bio">
    <h3 class="py-4">Bio</h3>
    <p><%= @user.bio %> </p>
  </div>
  <ul class="recent-posts">
    <% @user.recent_posts.each do |p| %>
      <li class="border border-1 border-dark container p-2 my-5 bio" >
        <div>
          <div>
            <%= link_to user_post_path(@user.id, p.id), id: "user_post#{p.id}" do %>
              <h4 class="py-4"><%= p.title %></h4>
            <% end %>
            <p><%= p.text.truncate(54) %> </p>
          <div>
          <div class="social-metrics d-flex justify-content-end gap-2 mr-3">
            <span>Comments: <%= p.comments.size %></span>
            <span>Likes: <%= p.likes.size %></span>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
  <div>
    <%= link_to "See all posts", user_posts_path(@user.id), class: "btn btn-primary d-flex justify-content-center align-self-center mb-5 button display" %>
  <div>
</div>